apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-umbrella
  namespace: argocd
spec:
  destination:
    namespace: webapp-umbrella
    server: 'https://kubernetes.default.svc'
  source:
    path: webapp/apps
    repoURL: 'https://github.com/shahgnp/helm-umbrella.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true