apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webapp-prod
  namespace: argocd
spec:
  destination:
    namespace: webapp-prod
    server: 'https://kubernetes.default.svc'
  source:
    path: webapp
    repoURL: 'https://github.com/shahgnp/helm-umbrella.git'
    targetRevision: HEAD
    helm:
      valueFiles:
      - values-prod.yaml
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true